on:
  push:
  workflow_dispatch:

env:
  mysqlpassword: hereisarandompassword
  create-database: CREATE DATABASE IF NOT EXISTS cbtnuggets;
  create-table: CREATE TABLE IF NOT EXISTS cbtnuggets.people (firstName varchar(30), lastName varchar(30));

jobs:
  svc-container:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - name: Connect to MySQL - Create database
      run: mysql --host=127.0.0.1 --password=${{ env.mysqlpassword }} --database=mysql --execute '${{ env.create-database }}'
    - name: Connect to MySQL - Create table
      run: mysql --host=127.0.0.1 --password=${{ env.mysqlpassword }} --database=mysql --execute '${{ env.create-table }}'
    services:
      database:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: ${{ env.mysqlpassword }}
        ports:
        - 3306:3306

      
